from typing import Any, Dict, Generator, Iterator


REDIRECT_STATI: Any
DEFAULT_REDIRECT_LIMIT: int
CONTENT_CHUNK_SIZE: Any
ITER_CHUNK_SIZE: int


class Response:
    __attrs__: Any
    status_code: Any
    headers: Any
    raw: Any
    url: Any
    encoding: Any
    history: Any
    reason: Any
    cookies: Any
    elapsed: Any
    request: Any
    def __init__(self) -> None: ...
    def __enter__(self) -> Response: ...
    def __exit__(self, *args: Any) -> None: ...
    def __bool__(self) -> bool: ...
    def __nonzero__(self) -> bool: ...
    def __iter__(self) -> Iterator[bytes | str]: ...
    @property
    def ok(self) -> bool: ...
    @property
    def is_redirect(self) -> bool: ...
    @property
    def is_permanent_redirect(self) -> bool: ...
    @property
    def next(self) -> Any: ...
    @property
    def apparent_encoding(self) -> Any: ...
    def iter_content(self, chunk_size: int = ..., decode_unicode: bool = ...) -> Generator[bytes | str, None, None]: ...
    def iter_lines(self, chunk_size: int=..., decode_unicode: bool = ..., delimiter: Any | None = ...) -> None: ...
    @property
    def content(self) -> bytes: ...
    @property
    def text(self) -> str: ...
    def json(self, **kwargs: Any) -> Any: ...
    @property
    def links(self) -> Dict[Any, Any]: ...
    def raise_for_status(self) -> None: ...
    def close(self) -> None: ...
