name: Set up VapourSynth
description: Build and install VapourSynth
inputs:
  vapoursynth-version:
    description: VapourSynth version
    required: true
runs:
  using: composite
  steps:
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: vapoursynth-${{ inputs.vapoursynth-version }}

    - name: Checkout zimg
      uses: actions/checkout@v5
      with:
        repository: sekrit-twc/zimg
        path: zimg
        submodules: recursive

    - name: Install zimg
      env:
        CC: ccache gcc
        CXX: ccache g++
      shell: bash
      run: |
        pushd zimg
        ./autogen.sh
        ./configure --prefix=/usr
        make -j$(nproc)
        sudo make install -j$(nproc)
        popd
        rm -rf zimg

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install Python dependencies
      shell: bash
      run: uv pip install --system -U cython==3.1.2 setuptools==80.9.0 wheel==0.45.1

    - name: Checkout VapourSynth
      uses: actions/checkout@v5
      with:
        repository: vapoursynth/vapoursynth
        ref: R${{ inputs.vapoursynth-version }}
        path: vapoursynth

    - name: Install VapourSynth
      env:
        CC: ccache gcc
        CXX: ccache g++
      shell: bash
      run: |
        pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr
        make -j$(nproc)
        sudo make install -j$(nproc)
        sudo mkdir -p /usr/lib/vapoursynth
        python setup.py sdist -d sdist
        mkdir empty
        pushd empty
        pip install vapoursynth --no-index --find-links ../sdist
        popd
        popd
        rm -rf vapoursynth

    - name: Verify VapourSynth install
      shell: python
      run: |
        import vapoursynth
        print(vapoursynth.core)
